

-- Limpieza segura (ignora errores si objetos no existen)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_INFORME_PLAGA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE INFORME_FITOSANITARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCCION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIE_PLAGA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE CAPACIDAD_LUGAR_ESPECIE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LUGAR_AREA_APOYO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LUGAR_PRODUCCION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ASISTENTE_TECNICO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCTOR CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PLAGA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PREDIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROPIETARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =======================================================
-- Dominios simples (tipos lógicos por CHECK)
-- =======================================================
-- Estados: A = activo, I = inactivo
-- Booleano Y/N: S = Sí, N = No

-- =======================================================
-- TABLAS MAESTRAS
-- =======================================================

CREATE TABLE PROPIETARIO (
  ID_PROPIETARIO       NUMBER(10)        PRIMARY KEY,
  TIPO_IDENTIDAD       VARCHAR2(10)      NOT NULL,
  NRO_IDENTIDAD        VARCHAR2(20)      NOT NULL,
  NOMBRE               VARCHAR2(120)     NOT NULL,
  DIRECCION            VARCHAR2(200),
  TELEFONO             VARCHAR2(30),
  EMAIL                VARCHAR2(120),
  CONSTRAINT UQ_PROP_DOC UNIQUE (TIPO_IDENTIDAD, NRO_IDENTIDAD)
);

CREATE TABLE PREDIO (
  ID_PREDIO            NUMBER(10)        PRIMARY KEY,
  NUMERO_PREDIAL       VARCHAR2(30)      NOT NULL,
  NOMBRE_PREDIAL       VARCHAR2(120),
  DEPARTAMENTO         VARCHAR2(80)      NOT NULL,
  MUNICIPIO            VARCHAR2(80)      NOT NULL,
  VEREDA               VARCHAR2(120),
  DIRECCION            VARCHAR2(200),
  LATITUD              NUMBER(10,6),
  LONGITUD             NUMBER(10,6),
  AREA_HA              NUMBER(10,2),
  NRO_REGISTRO_ICA     VARCHAR2(40),
  VERIFICADO           CHAR(1)           DEFAULT 'N' CHECK (VERIFICADO IN ('S','N')),
  ID_PROPIETARIO       NUMBER(10)        NOT NULL,
  CONSTRAINT UQ_PREDIO_NUM UNIQUE (NUMERO_PREDIAL),
  CONSTRAINT FK_PREDIO_PROPIETARIO FOREIGN KEY (ID_PROPIETARIO)
    REFERENCES PROPIETARIO (ID_PROPIETARIO)
);

CREATE TABLE PRODUCTOR (
  ID_PRODUCTOR         NUMBER(10)        PRIMARY KEY,
  TIPO_IDENTIDAD       VARCHAR2(10)      NOT NULL,
  NRO_IDENTIDAD        VARCHAR2(20)      NOT NULL,
  NOMBRE               VARCHAR2(120)     NOT NULL,
  DIRECCION            VARCHAR2(200),
  TELEFONO             VARCHAR2(30),
  EMAIL                VARCHAR2(120),
  NRO_REGISTRO_ICA     VARCHAR2(40),
  ESTADO               CHAR(1)           DEFAULT 'A' CHECK (ESTADO IN ('A','I')),
  CONSTRAINT UQ_PROD_DOC UNIQUE (TIPO_IDENTIDAD, NRO_IDENTIDAD)
);

CREATE TABLE ASISTENTE_TECNICO (
  ID_ASISTENTE_TECNICO NUMBER(10)        PRIMARY KEY,
  TIPO_IDENTIDAD       VARCHAR2(10)      NOT NULL,
  NRO_IDENTIDAD        VARCHAR2(20)      NOT NULL,
  NOMBRE               VARCHAR2(120)     NOT NULL,
  DIRECCION            VARCHAR2(200),
  TELEFONO             VARCHAR2(30),
  EMAIL                VARCHAR2(120),
  NRO_REGISTRO_PROF    VARCHAR2(40),
  NRO_REGISTRO_ICA     VARCHAR2(40),
  ESTADO               CHAR(1)           DEFAULT 'A' CHECK (ESTADO IN ('A','I')),
  CONSTRAINT UQ_AT_DOC UNIQUE (TIPO_IDENTIDAD, NRO_IDENTIDAD)
);

CREATE TABLE ESPECIE (
  ID_ESPECIE           NUMBER(10)        PRIMARY KEY,
  NOMBRE_CIENTIFICO    VARCHAR2(120)     NOT NULL,
  NOMBRE_COMUN         VARCHAR2(120),
  ESTADO               CHAR(1)           DEFAULT 'A' CHECK (ESTADO IN ('A','I')),
  CONSTRAINT UQ_ESPECIE_NC UNIQUE (NOMBRE_CIENTIFICO)
);

CREATE TABLE PLAGA (
  ID_PLAGA             NUMBER(10)        PRIMARY KEY,
  NOMBRE_CIENTIFICO    VARCHAR2(120)     NOT NULL,
  NOMBRES_COMUNES      VARCHAR2(200),
  ESTADO               CHAR(1)           DEFAULT 'A' CHECK (ESTADO IN ('A','I')),
  CONSTRAINT UQ_PLAGA_NC UNIQUE (NOMBRE_CIENTIFICO)
);

-- =======================================================
-- TABLAS DE NEGOCIO
-- =======================================================

CREATE TABLE LUGAR_PRODUCCION (
  ID_LUGAR             NUMBER(10)        PRIMARY KEY,
  NOMBRE               VARCHAR2(120)     NOT NULL,
  DEPARTAMENTO         VARCHAR2(80)      NOT NULL,
  MUNICIPIO            VARCHAR2(80)      NOT NULL,
  VEREDA               VARCHAR2(120),
  DIRECCION            VARCHAR2(200),
  LATITUD              NUMBER(10,6),
  LONGITUD             NUMBER(10,6),
  ID_PREDIO            NUMBER(10)        NOT NULL,
  ID_PRODUCTOR         NUMBER(10),
  ID_ASISTENTE_TECNICO NUMBER(10),
  NRO_REGISTRO_ICA_SITIO VARCHAR2(40),
  ESTADO               CHAR(1)           DEFAULT 'A' CHECK (ESTADO IN ('A','I')),
  CONSTRAINT UQ_LUGAR_NOMBRE_EN_PREDIO UNIQUE (ID_PREDIO, NOMBRE),
  CONSTRAINT FK_LUGAR_PREDIO FOREIGN KEY (ID_PREDIO)
    REFERENCES PREDIO (ID_PREDIO),
  CONSTRAINT FK_LUGAR_PRODUCTOR FOREIGN KEY (ID_PRODUCTOR)
    REFERENCES PRODUCTOR (ID_PRODUCTOR),
  CONSTRAINT FK_LUGAR_AT FOREIGN KEY (ID_ASISTENTE_TECNICO)
    REFERENCES ASISTENTE_TECNICO (ID_ASISTENTE_TECNICO)
);

CREATE TABLE LUGAR_AREA_APOYO (
  ID_AREA              NUMBER(10)        PRIMARY KEY,
  ID_LUGAR             NUMBER(10)        NOT NULL,
  TIPO_AREA            VARCHAR2(60)      NOT NULL, -- p.ej. BODEGA, LAVADO, EMPACADO
  CONSTRAINT FK_AREA_LUGAR FOREIGN KEY (ID_LUGAR)
    REFERENCES LUGAR_PRODUCCION (ID_LUGAR) ON DELETE CASCADE
);

CREATE TABLE CAPACIDAD_LUGAR_ESPECIE (
  ID_CAPACIDAD         NUMBER(10)        PRIMARY KEY,
  ID_LUGAR             NUMBER(10)        NOT NULL,
  ID_ESPECIE           NUMBER(10)        NOT NULL,
  CAPACIDAD_MAX_KG     NUMBER(12,2)      NOT NULL,
  CONSTRAINT UQ_CAP_LUGAR_ESPECIE UNIQUE (ID_LUGAR, ID_ESPECIE),
  CONSTRAINT FK_CAP_LUGAR FOREIGN KEY (ID_LUGAR)
    REFERENCES LUGAR_PRODUCCION (ID_LUGAR) ON DELETE CASCADE,
  CONSTRAINT FK_CAP_ESPECIE FOREIGN KEY (ID_ESPECIE)
    REFERENCES ESPECIE (ID_ESPECIE)
);

CREATE TABLE LOTE (
  ID_LOTE              NUMBER(10)        PRIMARY KEY,
  ID_LUGAR             NUMBER(10)        NOT NULL,
  ID_ESPECIE           NUMBER(10)        NOT NULL,
  VARIEDAD             VARCHAR2(120),
  AREA_HA              NUMBER(10,2),
  FECHA_SIEMBRA        DATE,
  FECHA_ELIMINACION    DATE,
  CONSTRAINT FK_LOTE_LUGAR FOREIGN KEY (ID_LUGAR)
    REFERENCES LUGAR_PRODUCCION (ID_LUGAR),
  CONSTRAINT FK_LOTE_ESPECIE FOREIGN KEY (ID_ESPECIE)
    REFERENCES ESPECIE (ID_ESPECIE)
);

CREATE TABLE PRODUCCION (
  ID_PROD              NUMBER(10)        PRIMARY KEY,
  ID_LOTE              NUMBER(10)        NOT NULL,
  FECHA_RECOLECCION    DATE              NOT NULL,
  CANTIDAD_KG          NUMBER(12,2)      NOT NULL,
  CONSTRAINT FK_PROD_LOTE FOREIGN KEY (ID_LOTE)
    REFERENCES LOTE (ID_LOTE) ON DELETE CASCADE
);

CREATE TABLE INFORME_FITOSANITARIO (
  ID_INFORME           NUMBER(10)        PRIMARY KEY,
  ID_LOTE              NUMBER(10)        NOT NULL,
  FECHA_INSPECCION     DATE              NOT NULL,
  OBSERVACION          VARCHAR2(1000),
  CANT_PLANTAS         NUMBER(10),
  CONSTRAINT FK_INF_LOTE FOREIGN KEY (ID_LOTE)
    REFERENCES LOTE (ID_LOTE) ON DELETE CASCADE
);

CREATE TABLE DETALLE_INFORME_PLAGA (
  ID_DETALLE           NUMBER(10)        PRIMARY KEY,
  ID_INFORME           NUMBER(10)        NOT NULL,
  ID_PLAGA             NUMBER(10)        NOT NULL,
  PLANTAS_INFECTADAS   NUMBER(10),
  PORCENTAJE_INFESTACION NUMBER(5,2), -- 0-100
  CONSTRAINT UQ_DET_INF_PLAGA UNIQUE (ID_INFORME, ID_PLAGA),
  CONSTRAINT FK_DET_INFORME FOREIGN KEY (ID_INFORME)
    REFERENCES INFORME_FITOSANITARIO (ID_INFORME) ON DELETE CASCADE,
  CONSTRAINT FK_DET_PLAGA FOREIGN KEY (ID_PLAGA)
    REFERENCES PLAGA (ID_PLAGA),
  CONSTRAINT CK_DET_PCT CHECK (PORCENTAJE_INFESTACION BETWEEN 0 AND 100)
);

CREATE TABLE ESPECIE_PLAGA (
  ID_ESPECIE           NUMBER(10)        NOT NULL,
  ID_PLAGA             NUMBER(10)        NOT NULL,
  CONSTRAINT PK_ESPECIE_PLAGA PRIMARY KEY (ID_ESPECIE, ID_PLAGA),
  CONSTRAINT FK_EP_ESPECIE FOREIGN KEY (ID_ESPECIE)
    REFERENCES ESPECIE (ID_ESPECIE) ON DELETE CASCADE,
  CONSTRAINT FK_EP_PLAGA FOREIGN KEY (ID_PLAGA)
    REFERENCES PLAGA (ID_PLAGA)
);

-- =======================================================
-- SECUENCIAS + DISPARADORES (auto-incremento estilo 10g)
-- =======================================================

-- Helper: crea secuencia y trigger para una tabla/columna
-- (No existe un "macro" en SQL*Plus; se listan explícitamente)

-- PROPIETARIO
CREATE SEQUENCE SEQ_PROPIETARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PROPIETARIO
BEFORE INSERT ON PROPIETARIO
FOR EACH ROW
WHEN (NEW.ID_PROPIETARIO IS NULL)
BEGIN
  SELECT SEQ_PROPIETARIO.NEXTVAL INTO :NEW.ID_PROPIETARIO FROM dual;
END;
/

-- PREDIO
CREATE SEQUENCE SEQ_PREDIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PREDIO
BEFORE INSERT ON PREDIO
FOR EACH ROW
WHEN (NEW.ID_PREDIO IS NULL)
BEGIN
  SELECT SEQ_PREDIO.NEXTVAL INTO :NEW.ID_PREDIO FROM dual;
END;
/

-- PRODUCTOR
CREATE SEQUENCE SEQ_PRODUCTOR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PRODUCTOR
BEFORE INSERT ON PRODUCTOR
FOR EACH ROW
WHEN (NEW.ID_PRODUCTOR IS NULL)
BEGIN
  SELECT SEQ_PRODUCTOR.NEXTVAL INTO :NEW.ID_PRODUCTOR FROM dual;
END;
/

-- ASISTENTE_TECNICO
CREATE SEQUENCE SEQ_ASISTENTE_TECNICO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_ASISTENTE_TECNICO
BEFORE INSERT ON ASISTENTE_TECNICO
FOR EACH ROW
WHEN (NEW.ID_ASISTENTE_TECNICO IS NULL)
BEGIN
  SELECT SEQ_ASISTENTE_TECNICO.NEXTVAL INTO :NEW.ID_ASISTENTE_TECNICO FROM dual;
END;
/

-- ESPECIE
CREATE SEQUENCE SEQ_ESPECIE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_ESPECIE
BEFORE INSERT ON ESPECIE
FOR EACH ROW
WHEN (NEW.ID_ESPECIE IS NULL)
BEGIN
  SELECT SEQ_ESPECIE.NEXTVAL INTO :NEW.ID_ESPECIE FROM dual;
END;
/

-- PLAGA
CREATE SEQUENCE SEQ_PLAGA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PLAGA
BEFORE INSERT ON PLAGA
FOR EACH ROW
WHEN (NEW.ID_PLAGA IS NULL)
BEGIN
  SELECT SEQ_PLAGA.NEXTVAL INTO :NEW.ID_PLAGA FROM dual;
END;
/

-- LUGAR_PRODUCCION
CREATE SEQUENCE SEQ_LUGAR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_LUGAR
BEFORE INSERT ON LUGAR_PRODUCCION
FOR EACH ROW
WHEN (NEW.ID_LUGAR IS NULL)
BEGIN
  SELECT SEQ_LUGAR.NEXTVAL INTO :NEW.ID_LUGAR FROM dual;
END;
/

-- LUGAR_AREA_APOYO
CREATE SEQUENCE SEQ_AREA_APOYO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_AREA_APOYO
BEFORE INSERT ON LUGAR_AREA_APOYO
FOR EACH ROW
WHEN (NEW.ID_AREA IS NULL)
BEGIN
  SELECT SEQ_AREA_APOYO.NEXTVAL INTO :NEW.ID_AREA FROM dual;
END;
/

-- CAPACIDAD_LUGAR_ESPECIE
CREATE SEQUENCE SEQ_CAPACIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_CAPACIDAD
BEFORE INSERT ON CAPACIDAD_LUGAR_ESPECIE
FOR EACH ROW
WHEN (NEW.ID_CAPACIDAD IS NULL)
BEGIN
  SELECT SEQ_CAPACIDAD.NEXTVAL INTO :NEW.ID_CAPACIDAD FROM dual;
END;
/

-- LOTE
CREATE SEQUENCE SEQ_LOTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_LOTE
BEFORE INSERT ON LOTE
FOR EACH ROW
WHEN (NEW.ID_LOTE IS NULL)
BEGIN
  SELECT SEQ_LOTE.NEXTVAL INTO :NEW.ID_LOTE FROM dual;
END;
/

-- PRODUCCION
CREATE SEQUENCE SEQ_PRODUCCION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PRODUCCION
BEFORE INSERT ON PRODUCCION
FOR EACH ROW
WHEN (NEW.ID_PROD IS NULL)
BEGIN
  SELECT SEQ_PRODUCCION.NEXTVAL INTO :NEW.ID_PROD FROM dual;
END;
/

-- INFORME_FITOSANITARIO
CREATE SEQUENCE SEQ_INFORME START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_INFORME
BEFORE INSERT ON INFORME_FITOSANITARIO
FOR EACH ROW
WHEN (NEW.ID_INFORME IS NULL)
BEGIN
  SELECT SEQ_INFORME.NEXTVAL INTO :NEW.ID_INFORME FROM dual;
END;
/

-- DETALLE_INFORME_PLAGA
CREATE SEQUENCE SEQ_DETALLE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_DETALLE
BEFORE INSERT ON DETALLE_INFORME_PLAGA
FOR EACH ROW
WHEN (NEW.ID_DETALLE IS NULL)
BEGIN
  SELECT SEQ_DETALLE.NEXTVAL INTO :NEW.ID_DETALLE FROM dual;
END;
/

-- =======================================================
-- ÍNDICES ÚTILES (consultas frecuentes)
-- =======================================================
CREATE INDEX IX_LUGAR_PREDIO ON LUGAR_PRODUCCION (ID_PREDIO);
CREATE INDEX IX_LOTE_LUGAR ON LOTE (ID_LUGAR);
CREATE INDEX IX_PRODUCCION_LOTE ON PRODUCCION (ID_LOTE);
CREATE INDEX IX_INF_LOTE ON INFORME_FITOSANITARIO (ID_LOTE);
CREATE INDEX IX_DET_INF ON DETALLE_INFORME_PLAGA (ID_INFORME);
CREATE INDEX IX_CAP_LUGAR ON CAPACIDAD_LUGAR_ESPECIE (ID_LUGAR);

-- =======================================================
-- DATOS DE EJEMPLO MÍNIMOS
-- =======================================================
INSERT INTO PROPIETARIO (TIPO_IDENTIDAD, NRO_IDENTIDAD, NOMBRE, TELEFONO, EMAIL)
VALUES ('CC','123456789','Pedro Pérez','3001234567','pedro@example.com');

INSERT INTO PREDIO (NUMERO_PREDIAL, NOMBRE_PREDIAL, DEPARTAMENTO, MUNICIPIO, ID_PROPIETARIO, VERIFICADO)
VALUES ('NP-001','Finca La Esperanza','Santander','Lebrija', 1, 'S');

INSERT INTO PRODUCTOR (TIPO_IDENTIDAD, NRO_IDENTIDAD, NOMBRE, ESTADO)
VALUES ('CC','987654321','María Gómez','A');

INSERT INTO ASISTENTE_TECNICO (TIPO_IDENTIDAD, NRO_IDENTIDAD, NOMBRE, ESTADO)
VALUES ('CC','11223344','Carlos Ruiz','A');

INSERT INTO ESPECIE (NOMBRE_CIENTIFICO, NOMBRE_COMUN) VALUES ('Musa paradisiaca','Banano');
INSERT INTO PLAGA (NOMBRE_CIENTIFICO, NOMBRES_COMUNES) VALUES ('Bemisia tabaci','Mosca blanca');

INSERT INTO LUGAR_PRODUCCION (NOMBRE, DEPARTAMENTO, MUNICIPIO, ID_PREDIO, ID_PRODUCTOR, ID_ASISTENTE_TECNICO, ESTADO)
VALUES ('Lote Norte','Santander','Lebrija', 1, 1, 1, 'A');

INSERT INTO LUGAR_AREA_APOYO (ID_LUGAR, TIPO_AREA) VALUES (1,'BODEGA');
INSERT INTO CAPACIDAD_LUGAR_ESPECIE (ID_LUGAR, ID_ESPECIE, CAPACIDAD_MAX_KG) VALUES (1,1,5000);

INSERT INTO LOTE (ID_LUGAR, ID_ESPECIE, VARIEDAD, AREA_HA, FECHA_SIEMBRA)
VALUES (1,1,'Gran Enano', 2.5, DATE '2025-01-15');

INSERT INTO PRODUCCION (ID_LOTE, FECHA_RECOLECCION, CANTIDAD_KG)
VALUES (1, DATE '2025-06-20', 1200);

INSERT INTO INFORME_FITOSANITARIO (ID_LOTE, FECHA_INSPECCION, OBSERVACION, CANT_PLANTAS)
VALUES (1, DATE '2025-06-22', 'Inspección periódica', 1500);

INSERT INTO DETALLE_INFORME_PLAGA (ID_INFORME, ID_PLAGA, PLANTAS_INFECTADAS, PORCENTAJE_INFESTACION)
VALUES (1,1,30,2.0);

INSERT INTO ESPECIE_PLAGA (ID_ESPECIE, ID_PLAGA) VALUES (1,1);

COMMIT;
